<a href="https://colab.research.google.com/github/AkshayK25/My_PythonCodeS/blob/master/numpy_indexing_and_slicing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
import numpy as np
n = int(input())
def tiling(n):
    result = np.zeros((n, n), dtype = int)
    result[::2, 1::2] = 1
    result[1::2, ::2] = 1
    return result
  
print(tiling(n))

4
[[0 1 0 1]
 [1 0 1 0]
 [0 1 0 1]
 [1 0 1 0]]


In [7]:
import numpy as np
n = 4
arr = ([0,1])
print(np.tile(arr,(n,n//2)))

[[0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]
 [0 1 0 1]]


**Border Rows and Columns**

Description

Extract all the border rows and columns from a 2-D array.

Format:

Input: A 2-D Python list

Output: Four NumPy arrays - First column of the input array, first row of the input array, last column of the input array, last row of the input array respectively.

Example:

Input 1:

[[11 12 13 14]

 [21 22 23 24]
 
 [31 32 33 34]]
 
Output 1:

[11 21 31]

[11 12 13 14]

[14 24 34]

[31 32 33 34]

Execution Time Limit
5 seconds

In [10]:
import numpy as np

input_list = [[11, 12, 13, 14],
 [21 ,22, 23, 24],
 [31, 32 ,33, 34]]

# Convert the input list to a NumPy array
array_2d =np.array(input_list)

# Extract the first column, first row, last column and last row respectively using
# appropriate indexing
row_first = array_2d[0:1,:]
col_first = array_2d[:,0:1]
col_last = array_2d[:,3:4]
row_last = array_2d[2:4,:]
colnew = col_first.reshape(1,3)
print(colnew[0])
print(row_first[0])
coll = col_last.reshape(1,3)
print(coll[0])
print(row_last[0])

[11 21 31]
[11 12 13 14]
[14 24 34]
[31 32 33 34]


In [6]:
import numpy as np
array_1= np.array([1, 2 ,3 ,5 ,4, 6 ,7 ,8, 5, 3, 2])
print(array_1[0::2])

[1 3 4 7 5 2]
